### ISSUE TITLE
Opayo provider callback fails

### ISSUE THREAD

**Issue by callumbwhyte** [vendrhub/vendr-payment-provider-opayo#4]
We have wired up our Opayo provider with Vendr v2 (on Umbraco 9) and currently can't process any payments.

Upon taking the card details Opayo tries to redirect back to the Vendr site.

We receive the following error:

![Screenshot 2021-10-14 at 21 41 19](https://user-images.githubusercontent.com/16511093/137392283-62f6dff1-e080-4b6d-a00c-df5fea7bc998.png)

This is because the callback URL that Vendr returns throws a 500 error.

I have investigated and found the error is a null reference, in `CallbackRequestModel.FromRequestAsync` the `request` parameter is null... Further digging brought me to looking at `PaymentProviderContext` in the Vendr Core, which has 2 internal constructors: one that takes a request, and one that passes `null` through for the request instead. The base payment provider uses the constructor without request and therefore the payment provider goes💥 when it calls `ProcessCallbackAsync`.

Previously in Vendr V1 the request was passed in to `ProcessCallback` as a parameter.

**Comment by mattbrailsford** [comment]
I believe this should be resolved in the current unstable feed. The problem was the new `PaymentProviderContext` wasn't being updated with the `request` object when it was converted into a stronly typed model. This has now been resolved.

There should be a 2.0.1 build on the unstable feed if you want to test it, otherwise the update will be pushed out some time this week.

**Comment by callumbwhyte** [comment]
@mattbrailsford We have upgraded to Vendr v2.0.2 and it definitely fixed something but still not quite right...

The request is there now, so no more nulls, but it's empty... No values whatsoever...

I've done some more digging and it seems the `RequestMessage` in the `VendrPaymentController` is the culprit. Creating an `HttpRequestMessageFeature` from an HTTP context results in an empty request, but by reading the request directly I was able to get all of the values. See below:

```
// this is empty
var ctxFormData = await ctx.Request.Content.ReadAsFormDataAsync();

// this has values
var httpFormData = await _httpContextAccessor.HttpContext.Request.ReadFormAsync();

// this is empty
var reqMsg = await new HttpRequestMessageFeature(_httpContextAccessor.HttpContext).HttpRequestMessage.Content.ReadAsFormDataAsync();
```

**Comment by mattbrailsford** [comment]
Yea, unfortunately `IHttpContextAccessor` isn't .NET Standard.

Usually if the `ReadAsFormDataAsync()` result is empty, this generally suggests the request body has already been processed somewhere as HttpRequestMessages can only have their body processed once. Looking at the code for the provider though, it does look as though it's only being called once in the codebase so I can't think why it would have already been processed 🤔

Have you modified the code in any way that would cause the `ctx.Request.Content` to be processed twice?

**Comment by callumbwhyte** [comment]
Worked through this with @mattbrailsford on Friday and confirm that v2.0.3 on the unstable feed has fixes for this!

Context: the `Content` stream used to get content from the HTTP request is being read by something, and can't be reset to the start of the stream when it gets re-read. This doesn't seem to have broken any other providers, so there's possibly some code in the Opayo provider actively reading the request more than once.

**Comment by mattbrailsford** [comment]
I personally think it might be the fact we have a `/umbraco/vendr/` based URL for the payment controller. This was by design as in v8 (not sure if it's still true in v9) this was the easiest way to have a URL that didn't need excluding from Umbraco via web.config. But my thinking is, because it starts `/umbraco` maybe some other Umbraco based middleware is running that reads the body and so it's getting read before it gets to us and thus can't be rewound.

My work around is to inject our own middleware that runs first and sees if it's a request for our API controller and if it is, enabled buffering on the request such that we CAN rewind the request.

I do wonder if changing urls to not have `/umbraco` in them might fix this, but I don't currently want to introduce a difference between v8 and v9 so we'll stick with this custom middleware for now.

**Comment by mattbrailsford** [comment]
Fix is in Vendr 2.0.3 release.
